15637/event/urls.py
from django.conf.urls import patterns, url
from django.utils import timezone

urlpatterns = patterns('',
    url(r'^create/$', 'event.views.create_event', name='create-event'),
    url(r'^edit/(?P<event_id>\d+)/$', 'event.views.edit_event', name='edit-event'),
    url(r'^view/(?P<event_id>\d+)/$', 'event.views.view_event', name='view-event'),


    url(r'^$', 'event.views.list_nearby_event', name='list-nearby-event'),
    url(r'^list/all/$', 'event.views.list_all_event', name='list-all-event'),
    url(r'^list/nearby/$', 'event.views.list_nearby_event', name='list-nearby-event'),
    url(r'^list/my/$', 'event.views.list_my_event', name='list-my-event'),

    url(r'^status/change/(?P<event_id>\d+)/$', 'event.views.change_status', name='change-event-status'),
    url(r'^status/query/(?P<event_id>\d+)/$', 'event.views.query_status', name='query-event-status'),
)

15637/eventhunter/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView 
from django.contrib import admin
import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'eventhunter.views.home', name='home'),
    # url(r'^eventhunter/', include('eventhunter.foo.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),


    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),

    url(r'^accounts/login/', 'register.views.custom_login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^accounts/', include('register.urls')),
    url(r'^event/', include('event.urls')),
    
    url(r'^profile/', include('simpleprofile.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #url(r'^$', direct_to_template, 
    #                { 'template': 'index.html' }, 'index'),
)

15637/event/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User

# Create your models here.
class Event(models.Model):
    INACTIVE = 0
    ACTIVE = 1
    STATUSES = (
            (INACTIVE, 'Inactive'),
            (ACTIVE, 'Active'),
            )
    eid = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, verbose_name="creator of this event")
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    status = models.IntegerField(default=ACTIVE, choices=STATUSES)
    create_time = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location = models.CharField(max_length=255)
    geo_location = models.PointField()
    objects = models.GeoManager()
    
    def __unicode__(self):
        return self.name + self.desc

class Activity(models.Model):
    JOIN = 0
    NOTJOIN = 1
    CHECKIN = 2
    CREAT = 3
    STATUSES = (
            (CHECKIN, 'Checkin'),
            (JOIN, 'Join'),
            (NOTJOIN, 'Notjoin'),
            (CREAT, 'Creat'),
            )

    class Meta:
        unique_together = ['user', 'event']

    user = models.ForeignKey(User, verbose_name="related user of this activity")
    event = models.ForeignKey(Event, verbose_name="related event of this activity")
    last_activity_time = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=JOIN, choices=STATUSES)

    def __unicode__(self):
        return self.user.username + self.event.name + self.status

15637/event/forms.py
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext_lazy as _
from datetime import datetime    
from models import Event, Activity
from django.contrib.gis.geos import GEOSGeometry

class CreateEventForm(forms.Form):
    """
    Form for creating a new event.
    
    Validates that the requested username is not already in use, and
    requires the password to be entered twice to catch typos.
    """
    name = forms.CharField(required=True,
            max_length=255,
            label=_("Event Name"),
            widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "Event name"})
            )

    desc = forms.CharField(max_length=255,
            label=_("Description"),
            widget=forms.Textarea(attrs={'class': "field span6" , 'rows': "4", 'placeholder': "Enter the description"})
            )


    start_time = forms.DateTimeField(required=True,
            label=_("Start Time"),
            widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "Start date and Time"})
            )

    end_time = forms.DateTimeField(required=True,
            label=_("End Time"),
            widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "End date and Time"})
            )

    location = forms.CharField(required=True,
            max_length=255,
            label=_("Location"),
            widget=forms.TextInput(attrs={'class': 'span6', 'placeholder': "Enter the location"})
            )

    lat = forms.FloatField(required=True,
            max_value=90.0,
            min_value= -90.0,
            widget=forms.TextInput(attrs={'type': 'hidden'})
            )

    lon = forms.FloatField(required=True,
            max_value=180.0,
            min_value= -180.0,
            widget=forms.TextInput(attrs={'type': 'hidden'})
            )

    def clean(self):
        """
        Verifiy that the start_time is no later than the end_time
        """
        cur_time = datetime.now()
        if 'start_time' in self.cleaned_data and 'end_time' in self.cleaned_data :
            if self.cleaned_data['start_time'].replace(tzinfo=None) < cur_time:
                raise forms.ValidationError(_("Start Time could not be earlier than the current time."))

            if self.cleaned_data['start_time'] > self.cleaned_data['end_time']:
                raise forms.ValidationError(_("Start Time could not be later than End Time."))
        return self.cleaned_data
 
    def save(self, user):
        lat = self.cleaned_data['lat']
        lon = self.cleaned_data['lon']
        new_event = Event(creator=user,
                name=self.cleaned_data['name'],
                desc=self.cleaned_data['desc'],
                status=Event.ACTIVE,
                start_time=self.cleaned_data['start_time'],
                end_time=self.cleaned_data['end_time'],
                location=self.cleaned_data['location'],
                geo_location=GEOSGeometry('POINT(%f %f)' % (lon, lat)),
                )

        new_event.save()
        activity, created = Activity.objects.get_or_create(user=user, event=new_event)
        activity.status = Activity.CREAT
        activity.save()
        return new_event;

class EditEventForm(forms.ModelForm):
    """
    Form for && editing an event.
    """
    name = forms.CharField(required=True,
            max_length=255,
            label=_("Event Name"),
            widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "Event name"})
            )

    desc = forms.CharField(max_length=255,
            label=_("Description"),
            widget=forms.Textarea(attrs={'class': "field span6" , 'rows': "4", 'placeholder': "Enter the description"})
            )


    start_time = forms.DateTimeField(required=True,
            label=_("Start Time"),
            widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "Start date and Time"})
            )

    end_time = forms.DateTimeField(required=True,
            label=_("End Time"),
            widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "End date and Time"})
            )

    def clean(self):
        """
        Verifiy that the start_time is no later than the end_time
        """
        cur_time = datetime.now()
        if 'start_time' in self.cleaned_data and 'end_time' in self.cleaned_data :
            if self.cleaned_data['start_time'].replace(tzinfo=None) < cur_time:
                raise forms.ValidationError(_("Start Time could not be later than the current time."))

            if self.cleaned_data['start_time'] > self.cleaned_data['end_time']:
                raise forms.ValidationError(_("Start Time could not be later than End Time."))
        return self.cleaned_data

    class Meta:
        model = Event 
        exclude = ('creator', 'geo_location', 'location', )

15637/event/views.py
# Create your views here.

from datetime import datetime    
from django.utils import timezone

from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from models import Event, Activity
from forms import CreateEventForm, EditEventForm
from django.core.context_processors import csrf
from django.contrib.gis.geos import fromstr
from django.contrib.gis.measure import D 
from django.utils import simplejson

@login_required
def create_event(request, success_url=None,
        template_name='event/create_event.html'):
    if request.method == 'POST':
        form = CreateEventForm(data=request.POST)
        if form.is_valid():
            new_event = form.save(request.user)
            if success_url is None:
                success_url = reverse('view-event', kwargs={'event_id' : new_event.eid })
            return redirect(success_url)
    else:
        form = CreateEventForm()

    return render(request, template_name, {'form':form,})

@login_required
def view_event(request, event_id,
        template_name='event/view_event.html'):
    cur_event = get_object_or_404(Event, eid=event_id)

    activities = Activity.objects.select_related().filter(event=cur_event,
            status__in=[Activity.JOIN, Activity.CHECKIN, Activity.CREAT],)

    return render(request, template_name, {'event':cur_event, 'activities' : activities,})

@login_required
def edit_event(request, event_id, success_url=None,
        template_name='event/edit_event.html'):

    cur_user = request.user
    event_obj = get_object_or_404(Event, eid=event_id)

    if success_url is None:
        success_url = reverse('view-event', kwargs={'event_id' : event_id})

    if (event_obj.creator != cur_user):
        return render(request, 'event/event_error.html', {'error' : 'You are not the creator of this event!'})

    if request.method == 'POST':
        form = EditEventForm(data=request.POST, files=request.FILES, instance=event_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)
    else:
        form = EditEventForm(instance=event_obj)
 
    return render(request, template_name, {'form': form, })

@login_required
def list_all_event(request, template_name='event/list_all_event.html'):
    """
    return all active events.
    """
    all_events = Event.objects.filter(status=Event.ACTIVE)
    return render(request, template_name, {'events':all_events})

@login_required
def list_nearby_event(request, template_name='event/list_nearby_event.html'):
    """
    Given a location and a radius (meter), return the closest number events.
    """
    lat = None
    lon=None 
    radius=5
    number=10
    if request.method == 'POST':
        lat = request.POST.get('lat', 0.0)
        lon = request.POST.get('lon', 0.0)
        radius = request.POST.get('radius', 5000)
        number = request.POST.get('number', 10)
    elif request.method == 'GET':
        lat = request.GET.get('lat', 0.0)
        lon = request.GET.get('lon', 0.0)
        radius = request.GET.get('radius', 5000)
        number = request.GET.get('number', 10)
    
    ref_pnt = fromstr("POINT(%s %s)" % (lon, lat))
    distance_from_point = {'m': radius}
    now_time = datetime.now()
    close_events = Event.objects.filter(geo_location__distance_lte=(ref_pnt, D(**distance_from_point)), end_time__gte=now_time)[:number]
    close_events_status = []

    if request.is_ajax():
        return HttpResponse(simplejson.dumps({
        'success': True,
        'events': serializers.serialize('json', close_events),
        'lat':lat, 
        'lon':lon,
        'uid': request.user.id
        }))

    return render(request, template_name, {'events':close_events, 'lat':lat, 'lon':lon})

@login_required
def list_my_event(request, template_name='event/list_my_event.html'):
    """
    Given a user, return the events created by or join by the user.
    """

    now_time = datetime.now()

    cur_user = request.user

    activities_expired = Activity.objects.select_related().filter(user=cur_user,
            status__in=[Activity.JOIN, Activity.CHECKIN, Activity.CREAT],
            event__end_time__lt=now_time)

    activities_happening = Activity.objects.select_related().filter(user=cur_user,
            status__in=[Activity.JOIN, Activity.CHECKIN, Activity.CREAT],
            event__start_time__lte=now_time,
            event__end_time__gte=now_time)

    activities_future= Activity.objects.select_related().filter(user=cur_user,
            status__in=[Activity.JOIN, Activity.CHECKIN, Activity.CREAT],
            event__start_time__gt=now_time)

    return render(request, template_name, {
        'activities_expired': activities_expired,
        'activities_happening': activities_happening,
        'activities_future': activities_future,
        }
        )

@login_required
def change_status(request, event_id, success_url=None,):
    """
    Given a user and an event, change the status of the related activity.
    """
    cur_user = request.user
    success = True
    error = ''
    status = Activity.NOTJOIN
    try:
        cur_event = Event.objects.get(eid=event_id)
        activity, created = Activity.objects.get_or_create(user=cur_user, event=cur_event)

        status = Activity.JOIN
        if request.method == 'POST':
            status = request.POST.get('status', Activity.JOIN)
        elif request.method == 'GET':
            status = request.GET.get('status', Activity.JOIN)
    
        activity.status = status
        status = activity.status
        activity.save()
    except Event.DoesNotExist:
        success = False
        error = 'Event does not exist.'

    if request.is_ajax():
        return HttpResponse(simplejson.dumps({
        'success': True,
        'error' : error,
        'status' : status
        }))


    if success_url is None:
        success_url = reverse('view-event', kwargs={'event_id': event_id})

    return redirect(success_url)

@login_required
def query_status(request, event_id, template_name='event/query_event_status.html'):
    """
    Given a user and an event, return the status of the related activity.
    """
    cur_user = request.user

    success = True
    error = ''
    joined_number = 0
    checkin_number = 0
    status = Activity.NOTJOIN
    is_creator = False

    try:
        cur_event = Event.objects.get(eid=event_id)
        if cur_event.creator == cur_user:
            is_creator = True

        joined_number = Activity.objects.filter(event__exact=cur_event, status__exact=Activity.JOIN).count()
        checkin_number = Activity.objects.filter(event__exact=cur_event, status__exact=Activity.CHECKIN).count()
        status = Activity.JOIN
        try:
            activity = Activity.objects.get(user=cur_user, event=cur_event)
            status = activity.status
        except Activity.DoesNotExist:
            status = Activity.NOTJOIN
    except Event.DoesNotExist:
        success = False
        error = 'Event does not exist.'

    if request.is_ajax():
        return HttpResponse(simplejson.dumps({
        'success': success,
        'error' : error,
        'is_creator': is_creator, 
        'status': status, 
        'joined_number' : joined_number,
        'checkin_number' : checkin_number,
        }))

    return HttpResponse(simplejson.dumps({
    'success': success,
    'error' : error,
    'is_creator': is_creator, 
    'status': status, 
    'joined_number' : joined_number,
    'checkin_number' : checkin_number,
    }))



    return render(request, template_name, {'status':status,})

15637/event/templates/event/create_event.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="page-header">
	<h1>
		Nearby Events <small>Create</small>
	</h1>
</div>
<form action="" method="post" id="event-form" class="form-horizontal">
	{% csrf_token %} {% if form.errors.items %}
	<div class="alert alert-error">
		{% for key, value in form.errors.items %} <a class="close"
			data-dismiss="alert">x</a> {{ value }} {% endfor %}
	</div>
	{% endif %}

	<div class="control-group">
		<label class="control-label" for="id_name">Event name:</label>
		<div class="controls">{{ form.name }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_desc">Description:</label>
		<div class="controls">{{ form.desc }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_start_time">Start:</label>
		<div id="startdatetimepicker" class="input-prepend date controls"
			style="margin-left: 20px;">
			<span class="add-on"> <i data-time-icon="icon-time"
				data-date-icon="icon-calendar"> </i>
			</span>{{ form.start_time }}
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_end_time">End:</label>
		<div id="enddatetimepicker" class="input-prepend date controls"
			style="margin-left: 20px;">
			<span class="add-on"> <i data-time-icon="icon-time"
				data-date-icon="icon-calendar"> </i>
			</span> {{ form.end_time }}
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_location">Location:</label>
		<div class="controls">{{ form.location }}</div>
	</div>
	<div class="form-actions">
		<button type="submit" class="btn btn-primary btn-large">Create</button>
		<button type="reset" class="btn">Reset</button>
	</div>
	{{ form.lat }} {{ form.lon }}
</form>
{% endblock %}

15637/event/templates/event/edit_event.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<!-- <h1>{{ lat }}</h1>
  <h1>{{ lon }}</h1>-->
<div class="page-header">
	<h1>
		Nearby Events <small>Edit</small>
	</h1>
</div>
<form action="" method="post" id="edit-event-form" class="form-horizontal">
	{% csrf_token %} {% if form.errors.items %}
	<div class="alert alert-error">
		{% for key, value in form.errors.items %} <a class="close"
			data-dismiss="alert">x</a> {{ value }} {% endfor %}
	</div>
	{% endif %}

	<div class="control-group">
		<label class="control-label" for="id_name">Event name:</label>
		<div class="controls">{{ form.name }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_desc">Description:</label>
		<div class="controls">{{ form.desc }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_status">Status:</label>
		<div class="controls">{{ form.status }}</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="id_start_time">Start:</label>
		<div id="startdatetimepicker" class="input-prepend date controls"
			style="margin-left: 20px;">
			<span class="add-on"> <i data-time-icon="icon-time"
				data-date-icon="icon-calendar"> </i>
			</span> {{ form.start_time }}
		</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_end_time">End:</label>
		<div id="enddatetimepicker" class="input-prepend date controls"
			style="margin-left: 20px;">
			<span class="add-on"> <i data-time-icon="icon-time"
				data-date-icon="icon-calendar"> </i>
			</span> {{ form.end_time }}
		</div>
	</div>
	<div class="form-actions">
		<button type="submit" class="btn btn-primary btn-large">Confirm</button>
		<button type="reset" class="btn">Reset</button>
	</div>
</form>

{% endblock %}

15637/event/templates/event/event_error.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h1> {{error}} </h1>

{% endblock %}

15637/event/templates/event/list_my_event.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="page-header">
	<h1>
		Nearby Events <small>Manage</small>
	</h1>
</div>


<div id="id_my_event" class="tab-pane active">
	<div class="tabbable tabs-left">
		<ul class="nav nav-tabs">
			<li class="active"><a data-toggle="tab" href="#lA">Future
					Events</a></li>
			<li><a data-toggle="tab" href="#lB">Happening Events</a></li>
			<li><a data-toggle="tab" href="#lC">Expired Events</a></li>
		</ul>
		<div class="tab-content">
			<div id="lA" class="tab-pane active">
				<table class="table">
					<thead>
						<tr>
							<th>Title</th>
							<th>Description</th>
							<th>Location</th>
							<th>Start</th>
							<th>End</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody>
						{% for activity in activities_future %} 
							{% if activity.status == 0 %}
								<tr class="success" href="../../view/{{ activity.event.eid }}">
							{% elif activity.status == 2 %}
								<tr class="warning" href="../../view/{{ activity.event.eid }}">
							{% else %}
								<tr class="info" href="../../view/{{ activity.event.eid }}">
							{% endif %}
							<td>{{ activity.event.name }}</td>
							<td>{{ activity.event.desc }}</td>
							<td>{{ activity.event.location }}</td>
							<td>{{ activity.event.start_time }}</td>
							<td>{{ activity.event.end_time }}</td> 
							{% if activity.status == 0 %}
								<td>Join</td> 
							{% elif activity.status == 2 %}
								<td>Check-in</td> 
							{% else %}
								<td>Create</td> 
							{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div id="lB" class="tab-pane">
				<table class="table">
					<thead>
						<tr>
							<th>Title</th>
							<th>Description</th>
							<th>Location</th>
							<th>Start</th>
							<th>End</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody>
						{% for activity in activities_happening %} 
							{% if activity.status == 0 %}
								<tr class="success" href="../../view/{{ activity.event.eid }}">
							{% elif activity.status == 2 %}
								<tr class="warning" href="../../view/{{ activity.event.eid }}">
							{% else %}
								<tr class="info" href="../../view/{{ activity.event.eid }}">
							{% endif %}
							<td>{{ activity.event.name }}</td>
							<td>{{ activity.event.desc }}</td>
							<td>{{ activity.event.location }}</td>
							<td>{{ activity.event.start_time }}</td>
							<td>{{ activity.event.end_time }}</td> 
							{% if activity.status == 0 %}
								<td>Join</td> 
							{% elif activity.status == 2 %}
								<td>Check-in</td> 
							{% else %}
								<td>Create</td> 
							{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
			<div id="lC" class="tab-pane">
				<table class="table">
					<thead>
						<tr>
							<th>Title</th>
							<th>Description</th>
							<th>Location</th>
							<th>Start</th>
							<th>End</th>
							<th>Status</th>
						</tr>
					</thead>
					<tbody>
						{% for activity in activities_expired %} 
							{% if activity.status == 0 %}
								<tr class="success" href="../../view/{{ activity.event.eid }}">
							{% elif activity.status == 2 %}
								<tr class="warning" href="../../view/{{ activity.event.eid }}">
							{% else %}
								<tr class="info" href="../../view/{{ activity.event.eid }}">
							{% endif %}
							<td>{{ activity.event.name }}</td>
							<td>{{ activity.event.desc }}</td>
							<td>{{ activity.event.location }}</td>
							<td>{{ activity.event.start_time }}</td>
							<td>{{ activity.event.end_time }}</td> 
							{% if activity.status == 0 %}
								<td>Join</td> 
							{% elif activity.status == 2 %}
								<td>Check-in</td> 
							{% else %}
								<td>Create</td> 
							{% endif %}
							</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

{% endblock %}

15637/event/templates/event/list_nearby_event.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<!-- <h1>{{ lat }}</h1>
  <h1>{{ lon }}</h1>-->
<div class="page-header">
	<h1>
		Nearby Events <small>Search</small>
	</h1>
</div>


<div class="row form-search">
	<div class="input-append span10">
		<input type="text" id="id_addressbar" name="addressbar"
			class="search-query span8" onkeypress="return runScript(event)">
		<button type="button" class="btn" onclick="return runScript()">Search
			Nearby</button>
	</div>
	<select id="id_radius" name="radius" class="span2">
		<option value="5000">&lt;&#61; 5 km</option>
		<option value="10000">&lt;&#61; 10 km</option>
		<option value="30000">&lt;&#61; 30 km</option>
		<option value="50000">&lt;&#61; 50 km</option>
		<option value="100000">&lt;&#61; 100 km</option>
	</select>
</div>
<br />
<div id="map-canvas"></div>
<!-- <ul>
	{% for event in events %}
	<li>{{ event.name }}</li> {% endfor %}
</ul>-->
{% endblock %}

15637/event/templates/event/view_event.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="page-header">
	<h1>
		Nearby Event <small>View</small>
	</h1>
</div>

<div id="event-view" class="row" style="font-size: 18px;">
	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Title: </strong>
		</div>
		<div class="span9">{{ event.name }}</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Description: </strong>
		</div>
		<div class="span9">{{ event.desc }}</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Start Time: </strong>
		</div>
		<div class="span9">{{ event.start_time }}</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>End Time: </strong>
		</div>
		<div class="span9">{{ event.end_time }}</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Location: </strong>
		</div>
		<div class="span9">{{ event.location }}</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Is Active: </strong>
		</div>
		<div class="span9">{% if event.status == 1 %} Yes {% else %} No
			{% endif %}</div>
	</div>

	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong># Participants: </strong>
		</div>
		<div class="span9">{{ activities|length }}</div>
	</div>

	{% if activities|length > 0 %}
	<div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Participants: </strong>
		</div>
		<div id="id_users" class="span9">
			{% for activity in activities %}
				<a href="{% url 'profiles_view_profile' activity.user.id %}">
					{{ activity.user }}
				</a>&nbsp;
			{% endfor %}
		</div>
	</div>
	<!-- <div class="row" style="margin-bottom: 5px;">
		<div class="span2 offset1" style="text-align: right;">
			<strong>Participants: </strong>
		</div>
		<div class="span9 btn-group">
			<button class="btn dropdown-toggle" data-toggle="dropdown">
				View User Profile <span class="caret"></span>
			</button>
			<ul class="dropdown-menu">
				{% for activity in activities %}
				<li><a
					href="{% url 'profiles_view_profile' activity.user.id %}">
						{{activity.user }} </a></li> {% endfor %}
			</ul>
		</div>
	</div>-->
	{% endif %} 
	
	{% if user == event.creator %}
	<div class="row" style="margin-top: 35px;">
		<div class="span2 offset4" style="text-align: right;">
			<a href="../../edit/{{ event.eid }}">
				<button id="editBtn" class="btn btn-primary btn-large">Edit</button>
			</a>
		</div>
	</div>
	{% endif %} 
	<input type="hidden" id="id_eid" name="eid" value="{{ event.eid }}" />
</div>

{% endblock %}