15637/event/urls.py
from django.conf.urls import patterns, url
from django.utils import timezone

urlpatterns = patterns('',
    url(r'^create/$', 'event.views.create_event', name='create-event'),
    url(r'^edit/(?P<event_id>\d+)/$', 'event.views.edit_event', name='edit-event'),
    url(r'^view/(?P<event_id>\d+)/$', 'event.views.view_event', name='view-event'),


    url(r'^$', 'event.views.list_nearby_event', name='list-nearby-event'),
    url(r'^list/all/$', 'event.views.list_all_event', name='list-all-event'),
    url(r'^list/nearby/$', 'event.views.list_nearby_event', name='list-nearby-event'),
    url(r'^list/my/$', 'event.views.list_my_event', name='list-my-event'),

    url(r'^status/change/(?P<event_id>\d+)/$', 'event.views.change_status', name='change-event-status'),
    url(r'^status/query/(?P<event_id>\d+)/$', 'event.views.query_status', name='query-event-status'),
)

15637/eventhunter/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView 
from django.contrib import admin
import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'eventhunter.views.home', name='home'),
    # url(r'^eventhunter/', include('eventhunter.foo.urls')),

    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),


    url(r'^$', TemplateView.as_view(template_name="index.html"), name='index'),
    url(r'^about/$', TemplateView.as_view(template_name="about.html"), name='about'),

    url(r'^accounts/login/', 'register.views.custom_login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),

    url(r'^accounts/', include('register.urls')),
    url(r'^event/', include('event.urls')),
    
    url(r'^profile/', include('simpleprofile.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    #url(r'^$', direct_to_template, 
    #                { 'template': 'index.html' }, 'index'),
)

15637/simpleprofile/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView 
from django.utils import timezone

urlpatterns = patterns('',
    url(r'^edit/$', 'simpleprofile.views.edit_profile', name='profiles_edit_profile'),
    url(r'^view/(?P<uid>\d+)/$', 'simpleprofile.views.profile_detail', name='profiles_view_profile'),
)

15637/event/models.py
from django.contrib.gis.db import models
from django.contrib.auth.models import User

# Create your models here.
class Event(models.Model):
    INACTIVE = 0
    ACTIVE = 1
    STATUSES = (
            (INACTIVE, 'Inactive'),
            (ACTIVE, 'Active'),
            )
    eid = models.AutoField(primary_key=True)
    creator = models.ForeignKey(User, verbose_name="creator of this event")
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    status = models.IntegerField(default=ACTIVE, choices=STATUSES)
    create_time = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    location = models.CharField(max_length=255)
    geo_location = models.PointField()
    objects = models.GeoManager()
    
    def __unicode__(self):
        return self.name + self.desc

class Activity(models.Model):
    JOIN = 0
    NOTJOIN = 1
    CHECKIN = 2
    CREAT = 3
    STATUSES = (
            (CHECKIN, 'Checkin'),
            (JOIN, 'Join'),
            (NOTJOIN, 'Notjoin'),
            (CREAT, 'Creat'),
            )

    class Meta:
        unique_together = ['user', 'event']

    user = models.ForeignKey(User, verbose_name="related user of this activity")
    event = models.ForeignKey(Event, verbose_name="related event of this activity")
    last_activity_time = models.DateTimeField(auto_now=True)
    status = models.IntegerField(default=JOIN, choices=STATUSES)

    def __unicode__(self):
        return self.user.username + self.event.name + self.status

15637/simpleprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from storage import OverwriteStorage

def profile_upload_to(instance, filename):
    return 'images/%s/%s' % (instance.user.username, filename)

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField(upload_to=profile_upload_to,storage=OverwriteStorage())
    first_name = models.CharField(max_length=63, blank=True)
    last_name = models.CharField(max_length=63, blank=True)
    home_addr = models.CharField(max_length=255, blank=True)
    self_desc = models.CharField(max_length=255, blank=True)
    allow_other_view = models.BooleanField(default=True)

15637/simpleprofile/forms.py
from django.contrib.auth.models import User
from django import forms
from django.utils.translation import ugettext_lazy as _
from datetime import datetime    
from models import UserProfile
from django.core.files.uploadedfile import InMemoryUploadedFile
import StringIO
from PIL import Image

def is_jpeg(file):
    try:
        img = Image.open(file)
        #return img.format == 'JPEG'
        return True
    except IOError:
        return False

def make_thumb_nail(file):
    try:
        img = Image.open(file)
        img.thumbnail((128, 128), Image.ANTIALIAS)
        thumbnailString = StringIO.StringIO()
        img.save(thumbnailString, 'JPEG')
        newFile = InMemoryUploadedFile(thumbnailString, None, 'temp.jpg', 'image/jpeg', thumbnailString.len, None)
        return newFile
    except IOError:
        return None


class ProfileForm(forms.ModelForm):
    """
    Form for creating && editing a user's profile.
    """
    first_name = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "First Name"}))
 
    last_name = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'class': 'input-xlarge', 'placeholder': "Last Name"}))
    
    self_desc = forms.CharField(max_length=255,
                                widget=forms.Textarea(attrs={'class': "field span6" , 'rows': "4", 'placeholder': "Enter the description"}))
    
    home_addr = forms.CharField(max_length=255,
                                widget=forms.TextInput(attrs={'class': 'span6', 'placeholder': "Enter the home address"}))

    image = forms.ImageField(required=False)

    def clean_image(self):
        file = self.cleaned_data['image']
        if file:
            try:
                img = Image.open(file)
                img.thumbnail((128, 128), Image.ANTIALIAS)
                thumbnailString = StringIO.StringIO()
                img.save(thumbnailString, 'JPEG')
                newFile = InMemoryUploadedFile(thumbnailString, None, 'temp.jpg', 'image/jpeg', thumbnailString.len, None)
                return newFile
            except IOError:
                raise forms.ValidationError(_("Only JPEG file is supported."))
        else:
            return file 

    class Meta:
        model = UserProfile
        exclude = ('user', 'avatar')

    def save(self, force_insert=False, force_update=False, commit=True):
        m = super(ProfileForm, self).save(commit=False)
        if self.cleaned_data['image']:
            #suf = make_thumb_nail(self.cleaned_data['image'])
            #if suf:
            #    m.avatar.save('%s_thumbnail.%s'%(m.user.username, 'jpeg'), suf, save=False)
            m.avatar.save('%s_thumbnail.%s'%(m.user.username, 'jpeg'), self.cleaned_data['image'], save=False)

        if commit:
            m.save()

        return m

15637/simpleprofile/views.py
# Create your views here.

from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.template import RequestContext

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from models import UserProfile 
from forms import ProfileForm

@login_required
def edit_profile(request, success_url=None,
                 template_name='profiles/edit_profile.html'):
    profile_obj = None
    cur_user = request.user
    try:
        profile_obj = cur_user.get_profile()
    except ObjectDoesNotExist:
        profile_obj = UserProfile.objects.create(user=cur_user)
    
    if success_url is None:
        success_url = reverse('profiles_view_profile',
                              kwargs={ 'uid': request.user.id})

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, files=request.FILES, instance=profile_obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(success_url)
    else:
        form = ProfileForm(instance=profile_obj)
   
    return render(request, template_name, { 'form': form, })

@login_required
def profile_detail(request, uid, 
                   template_name='profiles/view_profile.html'):
    
    profile_obj = None
    cur_user = request.user

    try:
        to_view_user = User.objects.get(pk=uid)
    except User.DoesNotExist:
        return render(request, 'profiles/error.html', {'error' : 'No such user!'})

    try:
        profile_obj = to_view_user.get_profile()
    except ObjectDoesNotExist:
        profile_obj = UserProfile.objects.create(user=to_view_user)

    if profile_obj.allow_other_view == False and profile_obj.user != cur_user:
        return render(request, 'profiles/error.html', {'error' : 'You are not allowed to view this guy\'s profile!'})

    return render(request, template_name, { 'profile': profile_obj, })

15637/simpleprofile/templates/profiles/edit_profile.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="page-header">
	<h1>
		My Profile <small>Edit</small>
	</h1>
</div>



<form action="" method="post" id="profile-form" class="form-horizontal" enctype="multipart/form-data">

	{% csrf_token %} {% if form.errors.items %}
	<div class="alert alert-error">
		{% for key, value in form.errors.items %} <a class="close"
			data-dismiss="alert">x</a> {{ value }} {% endfor %}
	</div>
	{% endif %}

	<div class="control-group">
		<label class="control-label" for="id_image">Avatar:</label>
		<div class="controls">{{ form.image }}</div>
	</div>

	<div class="control-group">
		<label class="control-label" for="id_first_name">First name:</label>
		<div class="controls">{{ form.first_name }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_last_name">Last name:</label>
		<div class="controls">{{ form.last_name }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_self_desc">Description: </label>
		<div class="controls">{{ form.self_desc }}</div>
	</div>
	<div class="control-group">
		<label class="control-label" for="id_home_addr">Home address:</label>
		<div class="controls">{{ form.home_addr }}</div>
	</div>

	<div class="control-group">
		<div class="controls">
			<label class="checkbox" for="id_allow_other_view"> {{ form.allow_other_view }} Allow other view </label>
		</div>
	</div>

	<div class="form-actions">
		<button type="submit" class="btn btn-primary btn-large">Confirm</button>
		<button type="reset" class="btn">Reset</button>
	</div>
</form>

{% endblock %}

15637/simpleprofile/templates/profiles/error.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="page-header">
	<h1>
		Profile <small>Error</small>
	</h1>
</div>
<h3> Oops...{{error}} </h3>

{% endblock %}

15637/simpleprofile/templates/profiles/view_profile.html
{% extends "base.html" %} {% load i18n %} {% block content %}
<div class="page-header">
	<h1>
	{% if user == profile.user %}
	My Profile
	{% else %}
	Profile
	{% endif %}
	<small>View</small>
	</h1>
</div>

<div class="row" style="font-size: 18px;">
	<div class="span2 offset2">
		{% if profile.avatar %}
			<img id="id_avatar" name="avatar" src="{{ profile.avatar.url }}" />
		{% else %}
			<img id="id_avatar" name="avatar" src="{{ MEDIA_URL }}images/default_thumbnail.jpeg" />
		{% endif %} 
	</div>

	<div class="span8">
		<div class="row" style="margin-bottom: 5px;">
			<div class="span2" style="text-align: right;">
				<strong>Username: </strong>
			</div>
			<div class="span6">{{ profile.user.username }}</div>
		</div>

		<div class="row" style="margin-bottom: 5px;">
			<div class="span2" style="text-align: right;">
				<strong>First name: </strong>
			</div>
			<div class="span6">{{ profile.first_name }}</div>
		</div>

		<div class="row" style="margin-bottom: 5px;">
			<div class="span2" style="text-align: right;">
				<strong>Last name: </strong>
			</div>
			<div class="span6">{{ profile.last_name }}</div>
		</div>

		<div class="row" style="margin-bottom: 5px;">
			<div class="span2" style="text-align: right;">
				<strong>Description: </strong>
			</div>
			<div class="span6">{{ profile.self_desc }}</div>
		</div>

		<div class="row" style="margin-bottom: 5px;">
			<div class="span2" style="text-align: right;">
				<strong>Address: </strong>
			</div>
			<div class="span6">{{ profile.home_addr }}</div>
		</div>
        
	{% if user == profile.user %}
		<div class="row" style="margin-top: 35px;">
			<div class="span1 offset1" style="text-align: right;">
				<a href="{% url 'profiles_edit_profile' %}"><button
						class="btn btn-primary btn-large">Edit</button></a>
			</div>
		</div>
	{% endif %}
	</div>
	<input type="hidden" id="id_eid" name="eid" value="{{ event.eid }}" />
</div>

{% endblock %}